version: '3.8'

services:
  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventorypass
    ports:
      - "3306:3306"
    volumes:
      - inventory-data:/var/lib/mysql
    networks:
      - scoobydoo

volumes:
  inventory-data:

networks:
  scoobydoo:
    external: true
