version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - /tmp/docker/mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: beauty_user
      MONGO_INITDB_ROOT_PASSWORD: beauty123
      MONGODB_AUTH_DATABASE: admin


