CREATE TABLE products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) UNIQUE,
    product_name TEXT,
    abbreviated_name TEXT,
    generic_name TEXT,
    quantity VARCHAR(100),
    brands TEXT,
    categories TEXT,
    categories_en TEXT,
    main_category TEXT,
    manufacturing_places TEXT,
    labels TEXT,
    ingredients_text TEXT,
    brand_owner TEXT,
    image_url TEXT,
    image_ingredients_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_code (code)
);
